
GET http://localhost:5276/weatherforecast/
Content-Type: application/json


GET {{URL}}/api/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


GET {{URL}}/api/users/5
Authorization: Bearer {{TOKEN}}
Content-Type: application/json


POST {{URL}}/api/account/register
Content-Type: application/json
{
    "userName": "John",
    "password": "strong_password"
}


POST {{URL}}/api/account/register
Content-Type: application/json
{
    "userName": "tomm",
    "password": "strong_password"
}

POST  {{URL}}/api/account/login
Content-Type: application/json
{
    "userName": "lisa",
    "password": "Pa$$word"
}


POST {{URL}}/api/account/register
Content-Type: application/json
{
    "userName": "newUser",
    "password": "password$1"
}

POST {{URL}}/api/account/login
Content-Type: application/json
{
    "userName": "tomm",
    "password": "strong_password"
}



GET {{URL}}/api/buggy/auth

GET {{URL}}/api/buggy/not-found

GET {{URL}}/api/buggy/server-error

GET {{URL}}/api/buggy/bad-request

GET {{URL}}/api/buggy/bad-request


POST {{URL}}/api/account/register
Content-Type: application/json
{
    "userName": "a",
    "password": "b$1"
}








