
api_HostAddress = http://localhost:5276


GET http://localhost:5276/weatherforecast/
Content-Type: application/json


GET {{api_HostAddress}}/api/users
Content-Type: application/json


GET {{api_HostAddress}}/api/users/5
Content-Type: application/json



POST {{api_HostAddress}}/api/account/register
Content-Type: application/json
{
    "userName": "John",
    "password": "strong_password"
}


POST {{api_HostAddress}}/api/account/register
Content-Type: application/json
{
    "userName": "tomm",
    "password": "strong_password"
}

POST  {{api_HostAddress}}/api/account/login
Content-Type: application/json
{
    "userName": "tomm",
    "password": "strong_password"
}


POST {{api_HostAddress}}/api/account/register
Content-Type: application/json
{
    "userName": "newUser",
    "password": "password$1"
}

POST {{api_HostAddress}}/api/account/login
Content-Type: application/json
{
    "userName": "tomm",
    "password": "strong_password"
}



GET {{api_HostAddress}}/api/buggy/auth

GET {{api_HostAddress}}/api/buggy/not-found

GET {{api_HostAddress}}/api/buggy/server-error

GET {{api_HostAddress}}/api/buggy/bad-request

GET {{api_HostAddress}}/api/buggy/bad-request


POST {{api_HostAddress}}/api/account/register
Content-Type: application/json
{
    "userName": "a",
    "password": "b$1"
}








